spring.application.name=parking-backend
server.port=8080
logging.level.com.parking=DEBUG

# JSP Configuration
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
server.servlet.jsp.init-parameters.development=true
spring.mvc.problemdetails.enabled=true
